// src/components/maps/NutsMap.jsx
import React, { useEffect, useRef, useContext, useMemo } from "react";
import { GeoJSON } from "react-leaflet";
import { ThemeContext } from "../../context/ThemeContext";
import { useTranslation } from "react-i18next";
import BaseMap from "./helpers/BaseMap";
import { t } from "i18next";

// Sequential color palette for highlighted regions (yellow to dark red)
const SELECTED_COLORS = ["#ffffb2", "#fecc5c", "#fd8d3c", "#f03b20", "#bd0026"];

// Geographical boundaries to restrict map panning within Europe
const EUROPE_BOUNDS = [
  [34.0, -25.0],
  [71.5, 45.0],
];

// ── Data Formatting Helpers ───────────────────────────────────────────────────

/**
 * @function getQuantileBreaks
 * @description Calculates quantile thresholds (breaks) to divide numerical data into roughly equal-sized groups.
 * @param {number[]} vals - Array of numerical values (e.g., median ages) from the selected sample.
 * @param {number} [classes=5] - Number of desired classification breaks.
 * @returns {number[]} Array of boundary values separating the quantiles.
 */
const getQuantileBreaks = (vals, classes = 5) => {
  if (vals.length === 0) return [];
  const sorted = [...vals].sort((a, b) => a - b);
  const breaks = [];
  for (let i = 1; i <= classes; i++)
    breaks.push(sorted[Math.floor((i / classes) * (sorted.length - 1))]);
  return breaks;
};

/**
 * @function getSelectedColor
 * @description Maps a given numerical value to a color from the predefined sequential palette based on computed quantile breaks.
 * @param {number} val - The specific value to be colored.
 * @param {number[]} breaks - Array of threshold values generated by getQuantileBreaks.
 * @returns {string} Hex color code.
 */
const getSelectedColor = (val, breaks) => {
  const i = breaks.findIndex((b) => val <= b);
  return SELECTED_COLORS[
    Math.min(i !== -1 ? i : breaks.length - 1, SELECTED_COLORS.length - 1)
  ];
};

// ── Legend Component ──────────────────────────────────────────────────────────

/**
 * @component SequentialLegend
 * @description Renders a color-coded legend for the sequentially colored sampled regions.
 * @param {Object} props
 * @param {number[]} props.colorBreaks - Array of calculated thresholds defining the color ranges.
 * @param {string} props.label - The localized title for the legend.
 */
function SequentialLegend({ colorBreaks, label }) {
  if (colorBreaks.length === 0) return null;
  return (
    <>
      <div className="fw-bold mb-1" style={{ fontSize: "0.78rem" }}>
        {label}
      </div>
      {colorBreaks.map((breakVal, i) => {
        const from = i === 0 ? breakVal - 10 : colorBreaks[i - 1];
        return (
          <div key={i} className="d-flex align-items-center gap-1 mb-1">
            <span
              style={{
                display: "inline-block",
                width: 13,
                height: 13,
                background:
                  SELECTED_COLORS[Math.min(i, SELECTED_COLORS.length - 1)],
                border: "1px solid #aaa",
                flexShrink: 0,
              }}
            />
            <span>
              {Number(from).toFixed(1)} – {Number(breakVal).toFixed(1)}{" "}
              {t("parameterEstimation.realDataSampling.stats.years")}
            </span>
          </div>
        );
      })}
    </>
  );
}

// ── Main Map Component ────────────────────────────────────────────────────────

/**
 * @component NutsMap
 * @description Renders an interactive choropleth map of EU NUTS3 regions specifically designed
 * for the real-data sampling simulation. It visually highlights the currently drawn sample and
 * supports two-way hover synchronization with external data tables.
 * * Note on interaction pattern:
 * - Hover state triggers tooltips and updates the external React state (setHoveredId).
 * - Changes to the selected sample (selectedIds) force a full remount of the GeoJSON layer
 * (via React key update) to ensure tooltips and styles are bound to the fresh data context.
 * * @param {Object} props
 * @param {Object} props.geoJsonData - FeatureCollection containing NUTS3 polygons and properties.
 * @param {string[]} props.selectedIds - Array of NUTS3 IDs currently included in the active sample.
 * @param {string|null} [props.hoveredId=null] - ID of the region currently hovered (driven by map or external table).
 * @param {Function} [props.onRegionHover=null] - Callback function to sync the hovered ID out to the parent component.
 */
function NutsMap({
  geoJsonData,
  selectedIds,
  hoveredId = null,
  onRegionHover = null,
}) {
  const { darkMode } = useContext(ThemeContext);
  const { t, i18n } = useTranslation();
  const geoJsonRef = useRef(null);

  const legendLabel = t("parameterEstimation.realDataSampling.map.legend");

  // O(1) lookup set for determining if a region is in the current sample
  const selectedSet = useMemo(() => new Set(selectedIds), [selectedIds]);

  // Recalculate color classes only when data or the sampled selection changes
  const colorBreaks = useMemo(() => {
    if (!geoJsonData || selectedSet.size === 0) return [];
    const vals = geoJsonData.features
      .filter((f) => selectedSet.has(f.properties.nuts_id))
      .map((f) => f.properties.median_age);
    return getQuantileBreaks(vals);
  }, [geoJsonData, selectedSet]);

  // Dynamic styling function evaluated for every polygon
  const style = (feature) => {
    const { nuts_id, median_age } = feature.properties;
    const isSelected = selectedSet.has(nuts_id);
    const isHovered = nuts_id === hoveredId;

    return {
      fillColor: isSelected
        ? getSelectedColor(median_age, colorBreaks)
        : darkMode
          ? "#2a2a2a"
          : "#e8e8e8",
      fillOpacity: isSelected ? (isHovered ? 1 : 0.85) : 0.4,
      weight: isHovered ? 3 : isSelected ? 1.5 : 0.3,
      color: isHovered
        ? "var(--bs-primary)"
        : isSelected
          ? darkMode
            ? "#fff"
            : "#555"
          : darkMode
            ? "#444"
            : "#bbb",
      opacity: 1,
    };
  };

  // Programmatically trigger style updates and layer sorting on hover without full remount
  useEffect(() => {
    if (!geoJsonRef.current) return;
    geoJsonRef.current.setStyle(style);
    if (hoveredId) {
      geoJsonRef.current.eachLayer((layer) => {
        if (layer.feature?.properties?.nuts_id === hoveredId)
          layer.bringToFront();
      });
    }
  }, [selectedSet, darkMode, colorBreaks, hoveredId]);

  /**
   * Binds tooltips and mouse events.
   * Due to the key prop on the GeoJSON component, this closure is always fresh
   * when selection changes, meaning we can directly use the stable React setter.
   */
  const onEachFeature = (feature, layer) => {
    const { name, country, median_age, nuts_id } = feature.properties;
    const isSelected = selectedSet.has(nuts_id);
    const tooltipAgeLabel = t(
      "parameterEstimation.realDataSampling.map.tooltipAge",
    );

    layer.bindTooltip(
      `<div class="text-center">
      <strong>${name}</strong><br/>
      <small class="text-muted">${country} · ${nuts_id}</small><br/>
      <span style="color:var(--bs-primary)"><strong>${tooltipAgeLabel} ${median_age} ${t("parameterEstimation.realDataSampling.stats.years")}</strong></span>
    </div>`,
      { sticky: false, className: "shadow-sm border-0 bg-body text-body" },
    );

    layer.on({
      mouseover: (e) => {
        if (geoJsonRef.current)
          geoJsonRef.current.eachLayer((l) => l.closeTooltip());
        layer.openTooltip(e.latlng);
        if (isSelected) onRegionHover?.(nuts_id);
      },
      mousemove: (e) => layer.openTooltip(e.latlng),
      mouseout: () => {
        layer.closeTooltip();
        onRegionHover?.(null);
      },
    });
  };

  const legend =
    colorBreaks.length > 0 ? (
      <SequentialLegend colorBreaks={colorBreaks} label={legendLabel} />
    ) : null;

  return (
    <BaseMap
      center={[50.5, 10.0]}
      zoom={4}
      minZoom={3}
      maxZoom={10}
      height={420}
      legend={legend}
      maxBounds={EUROPE_BOUNDS}
      maxBoundsViscosity={0.8}
    >
      {geoJsonData && (
        <GeoJSON
          ref={geoJsonRef}
          key={`${selectedIds.join(",")}-${darkMode ? "d" : "l"}-${i18n.language}`}
          data={geoJsonData}
          style={style}
          onEachFeature={onEachFeature}
        />
      )}
    </BaseMap>
  );
}

export default NutsMap;
